name: Deploy code

on: workflow_dispatch

env:
  REGISTRY: ghcr.io
  REPOSITORY: "serious-fin"
  PROJECT: qr-pastebin

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v5

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Add api .env file
        run: |
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> ./api/.env

      - name: Build API image
        run: |
          docker build ./api --tag ${{ env.REGISTRY }}/${{ env.REPOSITORY }}/${{ env.PROJECT }}-api:latest

      - name: Push API image to registry
        run: |
          docker push ${{ env.REGISTRY }}/${{ env.REPOSITORY }}/${{ env.PROJECT }}-api:latest

      - name: Update containers on server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            cd /root/qr-pastebin/api
            git pull
            echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

            docker compose -f compose.prod.yaml pull
            docker compose -f compose.prod.yaml up -d --remove-orphans --build --scale api=2

            docker image prune -f -a
